### ISSUE TITLE
BubbleSort

### ISSUE THREAD

**Issue by tomassirio** [PrajjwalPathak/C-Programs#7]
Adding a new BubbleSort program for HacktoberFest

**Comment by tomassirio** [comment]
Got the class created on [#8 ](https://github.com/PrajjwalPathak/C-Programs/pull/8)

**Comment by JossJoestar** [comment]
Can i help with this?

**Comment by PrajjwalPathak** [comment]
> Can i help with this?

You can contribute if you want.

**Comment by PrajjwalPathak** [comment]
> > Can i help with this?
> 
> You can contribute if you want.

I'm am closing this issue, but if anyone wants to contribute, they can.
